# Generated by Django 4.0.4 on 2022-05-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='static/logos/')),
                ('skill_name', models.CharField(max_length=200)),
            ],
        ),
    ]
