# Generated by Django 4.0.4 on 2022-05-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='logo',
        ),
    ]
