# Generated by Django 4.0.4 on 2022-05-21 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
