# Generated by Django 4.0.4 on 2022-05-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tech_stack',
            field=models.CharField(default='blank', max_length=500),
        ),
    ]
