# Generated by Django 4.0.4 on 2022-05-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projects_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tasks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
