# Generated by Django 4.0.4 on 2022-05-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projects_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='demo_link',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='projects',
            name='github_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
