# Generated by Django 4.0.4 on 2022-05-24 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_alter_experience_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='tasks',
        ),
    ]
