# Generated by Django 4.0.4 on 2022-05-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0009_alter_experience_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='date_range',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
