# Generated by Django 4.0.4 on 2022-05-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0002_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
