# Generated by Django 4.0.4 on 2022-05-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0003_remove_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default="Let's have coffee!", max_length=200),
        ),
    ]
