# Generated by Django 4.0.4 on 2022-05-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0005_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, default="Let's have coffee!", max_length=5000),
        ),
    ]
